name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v3
        id: dotnet
        with:
          dotnet-version: "6.0.x"
      - name: dotnet restore
        run: dotnet restore
      - name: dotnet build
        run: dotnet build /p:Platform="Any Cpu" /p:Configuration=Release
      - name: Archive nupkg files
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: |
            **/*.nupkg
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup ppa
        run: |
          sudo apt-get install software-properties-common -y
          sudo add-apt-repository ppa:robotraconteur/ppa -y
      - name: Install RR native packages
        run: sudo apt-get install robotraconteur-dev librobotraconteur-net-native
      - uses: actions/setup-dotnet@v3
        id: dotnet
        with:
          dotnet-version: "6.0.x"
      - name: dotnet restore
        run: dotnet restore
      - name: dotnet build
        run: dotnet build /p:Platform="Any Cpu" /p:Configuration=Release
          